import hashlib
import secrets
from datetime import datetime, timedelta, timezone
from typing import Any, Dict
from sqlalchemy.ext.asyncio import AsyncSession

from app.config.settings import settings
from app.db.repositories.user import UserRepository
from app.db.repositories.token import TokenRepository
from app.security.password import verify_password, hash_password
from app.security.jwt import create_access_token
from app.services.totp import (
    TOTPService,
    InvalidPasswordError,
    TwoFactorCodeRequiredError,
)


class InvalidCredentialsError(Exception):
    """
    Raised when the provided email or password is incorrect.
    """
    pass


class InvalidRefreshTokenError(Exception):
    """
    Raised when a refresh token does not exist or its user is missing.
    """
    pass


class ExpiredRefreshTokenError(Exception):
    """
    Raised when a refresh token has passed its expiration time.
    """
    pass


class RevokedRefreshTokenError(Exception):
    """
    Raised when a refresh token has already been revoked (e.g. rotated out,
    logged out, or invalidated when 2FA was enabled).
    """
    pass


class SamePasswordError(Exception):
    """
    Raised when a password change reuses the current password.
    """
    pass


class AuthService:
    def __init__(self, db: AsyncSession):
        self.db = db
        self.user_repo = UserRepository(db)
        self.token_repo = TokenRepository(db)

    def _hash_token(self, token: str) -> str:
        """
        Helper method to hash tokens securely using SHA-256.
        Since these tokens are high-entropy random strings generated by the system,
        SHA-256 is computationally fast, secure, and appropriate for database storage.
        """
        return hashlib.sha256(token.encode("utf-8")).hexdigest()

    async def login(self, email: str, password: str) -> Dict[str, Any]:
        """
        Executes the user login workflow:
        1. Find user by email (lowercased)
        2. Verify password
        3. Determine 2FA requirements:
           - If disabled: Issue JWT access token and store secure refresh token
           - If enabled: Generate a 5-minute single-use temporary login token
        """
        # Normalize email
        normalized_email = email.strip().lower()

        # 1. Fetch user
        user = await self.user_repo.get_by_email(normalized_email)
        if not user:
            raise InvalidCredentialsError()

        # 2. Verify password
        if not verify_password(password, user.password_hash):
            raise InvalidCredentialsError()

        # 3. Handle 2FA branch
        if user.is_2fa_enabled:
            # Generate a secure temporary login token
            plain_login_token = secrets.token_urlsafe(32)
            hashed_login_token = self._hash_token(plain_login_token)
            expires_at = datetime.now(timezone.utc) + timedelta(minutes=5)

            try:
                # Keep at most one active login token per user so the number of
                # TOTP guesses an attacker can obtain is bounded.
                await self.token_repo.invalidate_unused_login_tokens(user.id)
                await self.token_repo.create_login_token(
                    user_id=user.id,
                    token_hash=hashed_login_token,
                    expires_at=expires_at,
                )
                await self.db.commit()
            except Exception as e:
                await self.db.rollback()
                raise e

            return {
                "requires_2fa": True,
                "login_token": plain_login_token,
            }

        else:
            # Generate access and refresh tokens
            access_token = create_access_token(subject=user.id)
            plain_refresh_token = secrets.token_urlsafe(32)
            hashed_refresh_token = self._hash_token(plain_refresh_token)
            expires_at = datetime.now(timezone.utc) + timedelta(
                days=settings.REFRESH_TOKEN_EXPIRE_DAYS
            )

            try:
                await self.token_repo.create_refresh_token(
                    user_id=user.id,
                    token_hash=hashed_refresh_token,
                    expires_at=expires_at,
                )
                await self.db.commit()
            except Exception as e:
                await self.db.rollback()
                raise e

            return {
                "access_token": access_token,
                "refresh_token": plain_refresh_token,
                "token_type": "Bearer",
                "expires_in": settings.ACCESS_TOKEN_EXPIRE_MINUTES * 60,
            }

    async def refresh(self, refresh_token_plain: str) -> Dict[str, Any]:
        """
        Exchanges a valid refresh token for a new access token, rotating the
        refresh token in the process:
        1. Look up the refresh token by its hash.
        2. Reject if missing, revoked, or expired.
        3. Confirm the owning user still exists.
        4. Revoke the presented token and issue a brand-new access + refresh
           token pair (rotation), so a refresh token is single-use.
        """
        token_hash = self._hash_token(refresh_token_plain)
        db_token = await self.token_repo.get_refresh_token_by_hash(token_hash)

        if not db_token:
            raise InvalidRefreshTokenError()
        if db_token.revoked_at is not None:
            raise RevokedRefreshTokenError()
        if datetime.now(timezone.utc) > db_token.expires_at:
            raise ExpiredRefreshTokenError()

        user = await self.user_repo.get_by_id(db_token.user_id)
        if not user:
            raise InvalidRefreshTokenError()

        # Rotate: revoke the old token and mint a new pair.
        access_token = create_access_token(subject=user.id)
        new_plain_refresh_token = secrets.token_urlsafe(32)
        new_hashed_refresh_token = self._hash_token(new_plain_refresh_token)
        expires_at = datetime.now(timezone.utc) + timedelta(
            days=settings.REFRESH_TOKEN_EXPIRE_DAYS
        )

        try:
            await self.token_repo.revoke_refresh_token(db_token)
            await self.token_repo.create_refresh_token(
                user_id=user.id,
                token_hash=new_hashed_refresh_token,
                expires_at=expires_at,
            )
            await self.db.commit()
        except Exception as e:
            await self.db.rollback()
            raise e

        return {
            "access_token": access_token,
            "refresh_token": new_plain_refresh_token,
            "token_type": "Bearer",
            "expires_in": settings.ACCESS_TOKEN_EXPIRE_MINUTES * 60,
        }

    async def logout(
        self,
        refresh_token_plain: str,
        all_sessions: bool = False,
    ) -> None:
        """
        Revokes refresh tokens. The user is identified from the presented
        refresh token, so no access token is required (a client can log out
        even after its short-lived access token has expired).

        - The presented token must itself be currently valid (exists, not
          revoked, not expired); otherwise this is an idempotent no-op. This
          prevents an old/leaked token from being replayed to disrupt sessions.
        - all_sessions=True: revoke every active refresh token for that user.
        - otherwise: revoke only the presented refresh token.

        Always succeeds (idempotent) so it never leaks whether a token exists.
        """
        token_hash = self._hash_token(refresh_token_plain)
        db_token = await self.token_repo.get_refresh_token_by_hash(token_hash)

        # Only act on a currently-valid token; anything else is a silent no-op.
        if (
            not db_token
            or db_token.revoked_at is not None
            or datetime.now(timezone.utc) > db_token.expires_at
        ):
            return

        try:
            if all_sessions:
                await self.token_repo.revoke_user_refresh_tokens(db_token.user_id)
            else:
                await self.token_repo.revoke_refresh_token(db_token)
            await self.db.commit()
        except Exception as e:
            await self.db.rollback()
            raise e

    async def change_password(
        self,
        user,
        current_password: str,
        new_password: str,
        code: str | None = None,
    ) -> Dict[str, Any]:
        """
        Changes the authenticated user's password after a step-up re-verification:
        1. Confirm the current password.
        2. If 2FA is enabled, require and verify a TOTP code (shared lockout).
        3. Reject if the new password equals the current one.
        4. Hash and store the new password.
        5. Revoke ALL refresh tokens (security-state change), then issue a fresh
           access + refresh pair so the current device stays logged in while
           every other session is forced to re-authenticate.
        """
        if not verify_password(current_password, user.password_hash):
            raise InvalidPasswordError()

        if user.is_2fa_enabled:
            if not code:
                raise TwoFactorCodeRequiredError()
            totp_service = TOTPService(self.db)
            # Raises InvalidTOTPCodeError / TwoFactorLockedError on failure;
            # resets the shared attempt counter in memory on success.
            await totp_service.verify_totp_with_lockout(user, code)

        if new_password == current_password:
            raise SamePasswordError()

        user.password_hash = hash_password(new_password)

        access_token = create_access_token(subject=user.id)
        plain_refresh_token = secrets.token_urlsafe(32)
        hashed_refresh_token = self._hash_token(plain_refresh_token)
        expires_at = datetime.now(timezone.utc) + timedelta(
            days=settings.REFRESH_TOKEN_EXPIRE_DAYS
        )

        try:
            # Revoke first, then create the new token so it survives the sweep.
            await self.token_repo.revoke_user_refresh_tokens(user.id)
            await self.token_repo.create_refresh_token(
                user_id=user.id,
                token_hash=hashed_refresh_token,
                expires_at=expires_at,
            )
            await self.db.commit()
        except Exception as e:
            await self.db.rollback()
            raise e

        return {
            "access_token": access_token,
            "refresh_token": plain_refresh_token,
            "token_type": "Bearer",
            "expires_in": settings.ACCESS_TOKEN_EXPIRE_MINUTES * 60,
        }
