import hashlib
import secrets
from datetime import datetime, timedelta, timezone
from typing import Any, Dict
from sqlalchemy.ext.asyncio import AsyncSession

from app.config.settings import settings
from app.db.repositories.user import UserRepository
from app.db.repositories.token import TokenRepository
from app.security.password import verify_password
from app.security.jwt import create_access_token


class InvalidCredentialsError(Exception):
    """
    Raised when the provided email or password is incorrect.
    """
    pass


class AuthService:
    def __init__(self, db: AsyncSession):
        self.db = db
        self.user_repo = UserRepository(db)
        self.token_repo = TokenRepository(db)

    def _hash_token(self, token: str) -> str:
        """
        Helper method to hash tokens securely using SHA-256.
        Since these tokens are high-entropy random strings generated by the system,
        SHA-256 is computationally fast, secure, and appropriate for database storage.
        """
        return hashlib.sha256(token.encode("utf-8")).hexdigest()

    async def login(self, email: str, password: str) -> Dict[str, Any]:
        """
        Executes the user login workflow:
        1. Find user by email (lowercased)
        2. Verify password
        3. Determine 2FA requirements:
           - If disabled: Issue JWT access token and store secure refresh token
           - If enabled: Generate a 5-minute single-use temporary login token
        """
        # Normalize email
        normalized_email = email.strip().lower()

        # 1. Fetch user
        user = await self.user_repo.get_by_email(normalized_email)
        if not user:
            raise InvalidCredentialsError()

        # 2. Verify password
        if not verify_password(password, user.password_hash):
            raise InvalidCredentialsError()

        # 3. Handle 2FA branch
        if user.is_2fa_enabled:
            # Generate a secure temporary login token
            plain_login_token = secrets.token_urlsafe(32)
            hashed_login_token = self._hash_token(plain_login_token)
            expires_at = datetime.now(timezone.utc) + timedelta(minutes=5)

            try:
                await self.token_repo.create_login_token(
                    user_id=user.id,
                    token_hash=hashed_login_token,
                    expires_at=expires_at,
                )
                await self.db.commit()
            except Exception as e:
                await self.db.rollback()
                raise e

            return {
                "requires_2fa": True,
                "login_token": plain_login_token,
            }

        else:
            # Generate access and refresh tokens
            access_token = create_access_token(subject=user.id)
            plain_refresh_token = secrets.token_urlsafe(32)
            hashed_refresh_token = self._hash_token(plain_refresh_token)
            expires_at = datetime.now(timezone.utc) + timedelta(
                days=settings.REFRESH_TOKEN_EXPIRE_DAYS
            )

            try:
                await self.token_repo.create_refresh_token(
                    user_id=user.id,
                    token_hash=hashed_refresh_token,
                    expires_at=expires_at,
                )
                await self.db.commit()
            except Exception as e:
                await self.db.rollback()
                raise e

            return {
                "access_token": access_token,
                "refresh_token": plain_refresh_token,
                "token_type": "Bearer",
                "expires_in": settings.ACCESS_TOKEN_EXPIRE_MINUTES * 60,
            }
